version: '3'

services:
  db:
    image: postgres:12
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
